### PR TITLE
Add truffleruby to test matrix.

### PR DESCRIPTION
**Pull request by ioquatix**

### CODE REVIEW

**Comment by ioquatix** [comment]
@eregon this seems to be failing.

**Comment by eregon** [comment]
@ioquatix Could you create an issue on https://github.com/oracle/truffleruby/issues ?
That makes it so much easier to track :smiley:

**Comment by ioquatix** [comment]
This is now part of the github actions workflow on master.

**Comment by eregon** [comment]
Thanks, I filed https://github.com/oracle/truffleruby/issues/2045 to track the current failures.

**Pull request closed without merging**
