### PR TITLE
Test against `truffleruby-head`.

### PR DESCRIPTION
**Pull request by ioquatix**

### CODE REVIEW

**Comment by eregon** [comment]
The fix didn't make in the nightly build of yesterday (https://github.com/ruby/truffleruby-dev-builder/releases/tag/builds-20200709-170321).
The build of today will have it.

**Comment by eregon** [comment]
There is a new build now, could you restart the CI, or merge the PR?
I think it's worth merging because CI fails on the 20.1.0 release anyway.

**Comment by eregon** [comment]
@ioquatix Ping, can you restart the CI on this PR, or merge the PR?

**Comment by eregon** [comment]
I did a rerun in https://github.com/eregon/async-container/runs/884791368?check_suite_focus=true
The only failure is then:
```
Failures:

  1) Async::Container::Controller with signals restarts children when receiving SIGHUP
     Failure/Error: expect(input.read(2)).to be == 'I.'

       expected: == "I."
            got:    nil
     # ./spec/async/container/controller_spec.rb:129:in `block (3 levels) in <top (required)>'
     # <internal:core> core/kernel.rb:395:in `load'
     # <internal:core> core/kernel.rb:395:in `load'
     # <internal:core> core/kernel.rb:395:in `load'
     # <internal:core> core/kernel.rb:395:in `load'
     # <internal:core> core/kernel.rb:395:in `load'
     # <internal:core> core/kernel.rb:395:in `load'

Finished in 29.18 seconds (files took 3.83 seconds to load)
18 examples, 1 failure
```

Which is [the same as on JRuby](https://github.com/eregon/async-container/runs/884791372?check_suite_focus=true), so maybe this SIGHUP is not implemented for threaded containers? (or maybe the spec doesn't make sense for threaded?)

@ioquatix Can you merge this? Then there is only this one failure left to figure out.

**Comment by ioquatix** [comment]
It could be something weird with signal handling, I'll take a look. Sorry for the late reply, I've been pretty busy and missed the notifications.

**Comment by ioquatix** [comment]
It seems like SIGHUP (and SIGUSR2?) are not propagating out of `IO.select`.

@eregon Can you check it?

**Pull request merged**
